name: ci-dev

on:
  workflow_dispatch:
    inputs:
      ckb_light_client_url:
        description: 'CKB Light Client Repository URL'
        required: false
        default: 'https://github.com/nervosnetwork/ckb-light-client.git'
      ckb_light_client_branch:
        description: 'CKB Light Client Branch'
        required: false
        default: 'develop'
      rusqlite:
        description: 'Enable rusqlite feature'
        required: false
        default: ''
        type: string
  push:
    branches:
      - master
  pull_request:


jobs:
  npm-install-1:
    strategy:
      fail-fast: false
      matrix:
        net: ['testnet_v1']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: prepare env
        id: runtest
        env:
          CKB_LIGHT_CLIENT_URL: ${{ github.event.inputs.ckb_light_client_url || 'https://github.com/nervosnetwork/ckb-light-client.git' }}
          CKB_LIGHT_CLIENT_BRANCH: ${{ github.event.inputs.ckb_light_client_branch || 'develop' }}
          RUSQLITE: ${{ github.event.inputs.rusqlite }}
        run: |
          npm install --save-dev mocha @types/mocha chai @types/chai
          sh prepare_dev.sh
      - name: run test
        id: ci-test
        run: |
          npm run test-dev

      - name: Publish reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: mochawesome-report/
