name: ci-ckb-wasm

on:
  workflow_dispatch:
    inputs:
      ckb_light_client_url:
        description: 'CKB Light Client Repository URL'
        required: false
        default: 'https://github.com/Officeyutong/ckb-light-client.git'
      ckb_light_client_branch:
        description: 'CKB Light Client Branch'
        required: false
        default: 'use-trait-for-storage-functions'

  push:
    branches:
      - master
  pull_request:


jobs:
  npm-install-1:
    strategy:
      fail-fast: false
      matrix:
        net: ['testnet_v1']
        rusqlite: [true, false]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Node Cache
        uses: actions/cache@v4
        id: npm-and-yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('/home/runner/work/**/package-lock.json', '/home/runner/work/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: prepare env
        id: runtest
        env:
          CKB_LIGHT_CLIENT_URL: ${{ github.event.inputs.ckb_light_client_url || 'https://github.com/Officeyutong/ckb-light-client.git' }}
          CKB_LIGHT_CLIENT_BRANCH: ${{ github.event.inputs.ckb_light_client_branch || 'use-trait-for-storage-functions' }}
          RUSQLITE: ${{ matrix.rusqlite && '1' || '' }}
        run: |
          npm install --save-dev mocha @types/mocha chai @types/chai
          bash prepare_wasm.sh
      - name: run test
        id: ci-test
        run: |
          npm run test-wasm

      - name: Publish reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: mochawesome-report/
